language: php

notifications:
  email:
    - travis-ci@pimcore.org

php:
  - 7
  - 7.1

services:
  - mysql

cache:
  directories:
    - vendor

env:
  - PIMCORE_ENVIRONMENT=test PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test" PIMCORE_TEST_CACHE_REDIS_DB=1

#before_install:
#  # analyze ZF usage before running anything else
#  - if [[ "$TRAVIS_PHP_VERSION" == "7" ]]; then bash .travis/analyze-zf-usage.sh; fi

before_install:
  - mysql -e "CREATE DATABASE $PIMCORE_TEST_DB_DBNAME;"

install:
  # add config template
  - mkdir -p var/config
  - cp .travis/system.template.php var/config/system.php

  # install composer - HHVM isn't officially PHP 7 compatible - see https://github.com/composer/composer/issues/4976
  - if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then composer install; fi
  - if [[ "$TRAVIS_PHP_VERSION" == *"hhvm"* ]]; then composer install --ignore-platform-reqs; fi

before_script:
  # install apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo a2enmod rewrite actions fastcgi alias

  # customize php settings
  - sudo chmod 0755 .travis/setup-fpm.sh .travis/setup-hhvm.sh
  - if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then .travis/setup-fpm.sh; fi
  - if [[ "$TRAVIS_PHP_VERSION" == *"hhvm"* ]]; then .travis/setup-hhvm.sh; fi

  # configure apache virtual hosts - config was copied in the individual setup scripts above (FPM/HHVM)
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

script:
  - if [[ "$TRAVIS_PHP_VERSION" != *"hhvm"* ]]; then php  vendor/bin/codecept run -c pimcore --json; fi
  - if [[ "$TRAVIS_PHP_VERSION" == *"hhvm"* ]]; then hhvm vendor/bin/codecept run -c pimcore --json; fi

after_script:
  - cat $TRAVIS_BUILD_DIR/var/logs/test.log
  - cat $TRAVIS_BUILD_DIR/apache-error.log
  - cat $TRAVIS_BUILD_DIR/apache-access.log
  #- cat /tmp/hhvm.log
