name: Propagate release from EE to CE

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
      release_body:
        description: 'Release body contents'
        required: true
      release_name:
        description: 'Release name'
        required: true
      sha:
        description: 'SHA hash of the release tag'
        required: true

jobs:
  check-tag-val:
    env:
      TAG_NAME: ${{ github.event.inputs.tag_name }}
    if: github.repository == 'pimcore/ee-pimcore'
    runs-on: ubuntu-latest
    outputs:
      isTagValid: ${{ steps.check.outputs.isTagValid }}
    steps:
    - name: Check tag format to accept major and minor and exclude patches
      id: check
      run: |
        if [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+(\.0)?$ ]]; then
          echo "isTagValid=true" >> $GITHUB_OUTPUT
        else
          echo "isTagValid=false" >> $GITHUB_OUTPUT
          exit 1
        fi

  propagate-release-to-ce:
    needs: check-tag-val
    if: github.repository == 'pimcore/ee-pimcore' && needs.check-tag-val.outputs.isTagValid == 'true'
    uses: pimcore/workflows-centralized/.github/workflows/parent-release-propagate.yml@v1.0.0-rc.5
    with:
      tag_name: ${{ inputs.tag_name }}
      release_body : ${{ inputs.release_body}}
      release_name: ${{ inputs.release_name }}
      sha: ${{ inputs.sha }}
      target_repo: 'pimcore'
    secrets:
      token: ${{ secrets.SYNC_TOKEN }}